# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-23 08:36
from __future__ import unicode_literals

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_remove_contactinfo_created_when'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128),
        ),
    ]
